version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the application..."
      - npm run build || echo "No build script found, skipping..."

  post_build:
    commands:
      - echo "Build complete, preparing for deployment..."
      - zip -r app.zip .
      - aws s3 cp app.zip s3://myapp-deployment-bucket-6semcse/

artifacts:
  files:
    - app.zip

